articles/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from articles.api import ArticleViewSet, ArticleOnlyByUserView
from articles.views import HomeView, ArticleView, ArticlesByUserView, ArticlesByCategoryView, ArticlesBySearchQueryView

router = DefaultRouter()
router.register('apiv1/article', ArticleViewSet, 'api_articles_')

articles_urls = [

    # Urls WEB
    url(r'^$', HomeView.as_view(), name='site_home'),
    url(r'^category\/(?P<slug>[A-Za-z0-9.\+@_-]+)\/$', ArticlesByCategoryView.as_view(), name='articles_by_category'),
    url(r'^search\/$', ArticlesBySearchQueryView.as_view(), name='articles_by_search_query'),
    url(r'^(?P<nombre_de_usuario>[A-Za-z0-9.\+@_-]+)\/$', ArticlesByUserView.as_view(), name='articles_by_user'),
    url(r'^(?P<nombre_de_usuario>[A-Za-z0-9.\+@_-]+)\/(?P<articulo_slug>[A-Za-z0-9.\+@_-]+)$', ArticleView.as_view(), name='article_detail'),

    # URLS APis
    url(r'', include(router.urls)),
    url(r'^apiv1/articleuser/$', ArticleOnlyByUserView.as_view()),

]

users/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token
from users.api import UserViewSet, ApiLogin

__author__ = 'Javier Ruiz'

router = DefaultRouter()
router.register('apiv1/users', UserViewSet, base_name='api_users_')

urlpatterns = [
    # Web URLS

    # API URLS
    url(r'', include(router.urls)),
    # url(r'^apiv1/users/login$', obtain_jwt_token),
    url(r'^apiv1/users/login$', ApiLogin.as_view()),

]

welldone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from django.utils.translation import ugettext as _
from users import urls as users_urls
from articles.urls import articles_urls
from Comments.urls import comments_urls
from Favourites.urls import favourites_urls
from Follows.url import follows_urls
from Underlines.url import underlines_urls
from users.form import MyExtendedForm
from Category.urls import category_urls
from registration.backends.default.views import RegistrationView

router = DefaultRouter()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Static
    url(r'^accounts/register/$', RegistrationView.as_view(), {
        'form': MyExtendedForm
    }),
    url(r'^accounts/', include('registration.backends.default.urls')),

    #robots.txt
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),

    # API
    url(r'', include(articles_urls)), #aquí está la home
    url(r'', include(users_urls)),
    url(r'', include(comments_urls)),
    url(r'', include(favourites_urls)),
    url(r'', include(follows_urls)),
    url(r'', include(underlines_urls)),
    url(r'', include(category_urls)),
    url(r'', include(router.urls))
]


# variable de prueba de traduccion

cadena = _("Hola a todos, primera cadena traducida, Kerberos TEAM")
print(cadena)

Favourites/models.py
from django.db import models
from articles.models import Article
from django.contrib.auth.models import User

# Create your models here.

class Favourite(models.Model):
    owner = models.ForeignKey(User, default=1)
    article = models.ForeignKey(Article, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.article.title

    class Meta:
        ordering = ('created_at',)

articles/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.template import defaultfilters

from articles.validators import badwords
from Category.models import Category
from config.constants import VISIBILITY, VISIBILITY_PUBLIC, STATUS, STATUS_PUBLICATED


class Article(models.Model):
    owner = models.ForeignKey(User, default=1)
    title = models.CharField(max_length=100, null=False, blank=False, default='Titulo', validators=[badwords])
    introduction = models.CharField(max_length=200, null=True, validators=[badwords])
    body = models.TextField(null=False, blank=False, default='Cuerpo del post', validators=[badwords])
    media_url = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    publicated_at = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category)
    likes = models.CharField(max_length=10, null=False, default='0')
    dislikes = models.CharField(max_length=10, null=False, default='0')
    visibility = models.CharField(max_length=3, choices=VISIBILITY, default=VISIBILITY_PUBLIC)
    status_pub = models.CharField(max_length=3, choices=STATUS, default=STATUS_PUBLICATED)
    is_response_to = models.ForeignKey('self', null=True, blank=True)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = defaultfilters.slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ('created_at',)

articles/views.py
# -*- encoding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseNotFound
from django.shortcuts import render
from django.utils import translation
from django.utils.decorators import method_decorator
from django.views import View

from Category.models import Category
from Comments.forms import CommentForm
from Comments.models import Comment
from Underlines.models import Underline
from articles.models import Article
from django.utils import timezone
from common.utils import pagination
from config.constants import ITEMS_PER_PAGE
from django.utils.translation import ugettext as _


class ArticlesQuerySet(object):

    @staticmethod
    def get_articles_publicated():
        return Article.objects.filter(publicated_at__lt=timezone.now()).order_by('-publicated_at')

    @staticmethod
    def get_articles_only_by_user(user):
        possible_articles = Article.objects.all().select_related("owner").order_by("-modified_at")
        if not user.is_authenticated():
            possible_articles = None
        else:
            possible_articles = possible_articles.filter(Q(owner=user))
        return possible_articles

    def get_articles_by_user(user, logged_user):
        articles = None
        if logged_user.is_superuser or user[0]==logged_user:
            articles = Article.objects.filter(owner=user)
        else:
            articles = Article.objects.filter(owner=user, publicated_at__lt=timezone.now())
        return articles.order_by('-publicated_at')

    def get_articles_by_category(category):
        articles = None
        articles = Article.objects.filter(category__id=category, publicated_at__lt=timezone.now())
        return articles.order_by('-publicated_at')


    def get_articles_by_search_query(search_string):
        articles = None
        articles = Article.objects.filter(Q(title__contains=search_string) | Q(body__contains=search_string) | Q(introduction__contains=search_string))
        return articles.order_by('-publicated_at')


    @staticmethod
    def get_article(slug, logged_user):
        articles = Article.objects.filter(slug=slug)
        if logged_user.is_superuser or articles[0].owner == logged_user or articles[0].publicated_at<timezone.now():
            return articles
        else:
            return Article.objects.none()


class HomeView(View):

    def get(self, request):
        """
        Renderiza el home con los últimos posts
        :param request: objeto HttpRequest con los datos de la petición
        :return: objeto HttpResponse con los datos de la respuesta
        """

        # fuerza cambio de idioma
        forced_language = request.GET.get('lang')
        if forced_language:
            request.session['lang'] = forced_language

        session_lang = request.session.get('lang')
        if session_lang:
            translation.activate(session_lang)
            request.session[translation.LANGUAGE_SESSION_KEY] = session_lang


        # recupera todos los articulos publicados
        articles_list = ArticlesQuerySet.get_articles_publicated()

        articles = pagination.get_selected_page(articles_list, ITEMS_PER_PAGE, request.GET.get('page'))

        context = {'articles_list': articles}

        return render(request, 'articles/home.html', context)


class ArticlesByUserView(View):

    def get(self, request, nombre_de_usuario):
        """
        Renderiza todos los posts de un usuario
        :param request: objeto HttpRequest con los datos de la petición
        :return: objeto HttpResponse con los datos de la respuesta
        """
        # comprueba que el usuario exista
        user = User.objects.filter(username=nombre_de_usuario)
        if len(user) == 0:
            return HttpResponseNotFound(_("El usuario que buscas no existe"))
        elif len(user) > 1:
            return HttpResponse(_("Múltiples opciones"), status=300)

        # TODO: Los usuarios deberían ir "slugifados"
        articles_list = ArticlesQuerySet.get_articles_by_user(user, request.user)

        articles = pagination.get_selected_page(articles_list, ITEMS_PER_PAGE, request.GET.get('page'))

        context = {'articles_list': articles, 'usuario': user[0]}
        return render(request, 'articles/articles_by_user.html', context)


class ArticlesByCategoryView(View):

    def get(self, request, slug):
        """
        Renderiza todos los posts de un usuario
        :param request: objeto HttpRequest con los datos de la petición
        :return: objeto HttpResponse con los datos de la respuesta
        """
        # comprueba que la categoria
        category = Category.objects.filter(slug=slug)
        if len(category) == 0:
            return HttpResponseNotFound(_("La categoria que buscas no existe"))
        elif len(category) > 1:
            return HttpResponse(_("Múltiples opciones"), status=300)

        articles_list = ArticlesQuerySet.get_articles_by_category(category)

        articles = pagination.get_selected_page(articles_list, ITEMS_PER_PAGE, request.GET.get('page'))

        context = {'articles_list': articles, 'categoria': category[0]}
        return render(request, 'articles/articles_by_category.html', context)


class ArticlesBySearchQueryView(View):

    def get(self, request):
        """
        Renderiza todos los posts de un usuario
        :param request: objeto HttpRequest con los datos de la petición
        :return: objeto HttpResponse con los datos de la respuesta
        """

        query = request.GET.get("q", "")
        if not query:
            return HttpResponseNotFound(_("Debe especificar una cadena de búsqueda"))

        articles_list = ArticlesQuerySet.get_articles_by_search_query(query)

        articles = pagination.get_selected_page(articles_list, ITEMS_PER_PAGE, request.GET.get('page'))

        context = {'articles_list': articles, 'search_query': query}
        return render(request, 'articles/articles_by_search_query.html', context)


class ArticleView(View):

    def get(self, request, nombre_de_usuario, articulo_slug):
        """
        Renderiza un post
        :param request: objeto HttpRequest con los datos de la petición
        :return: objeto HttpResponse con los datos de la respuesta
        """
        new_comment_form = CommentForm()

        return self.common(request, nombre_de_usuario, articulo_slug, new_comment_form)

    def common(self, request, nombre_de_usuario, articulo_slug, form, error = ''):
        """
        Ejecuta la parte que es común a las llamadas GET y POST
        :param request: objeto HttpRequest con los datos de la petición
        :return: objeto HttpResponse con los datos de la respuesta
        """
        # se asegura de que el autor exista
        article = self.get_current_article(request, nombre_de_usuario, articulo_slug)

        underlines = Underline.objects.filter(article=article)
        for underline in underlines:
            replacement = '<span class="underlined_text{0}">{1}</span>'.format(
                ' mine' if underline.owner == request.user else '',
                underline.text
            )
            article.body = article.body.replace(underline.text, replacement)

        context = {}
        context = {'article': article,
                   'form': form,
                   'error': error}

        return render(request, 'articles/article_detail.html', context)

    def get_current_article(self, request, nombre_de_usuario, articulo_slug):
        user = User.objects.filter(username=nombre_de_usuario)
        if len(user) == 0:
            return HttpResponseNotFound(_("El usuario que buscas no existe"))
        elif len(user) > 1:
            return HttpResponse(_("Múltiples opciones"), status=300)

        articles = ArticlesQuerySet.get_article(articulo_slug, request.user).filter(owner=user)

        if len(articles) == 0:
            return HttpResponseNotFound(_("El artículo que buscas no existe"))
        elif len(articles) > 1:
            return HttpResponse(_("Múltiples opciones"), status=300)

        return articles[0]


    @method_decorator(login_required())
    def post(self, request, nombre_de_usuario, articulo_slug):
        """
        Valida la petición, y crea el comentario asociado al user logado y el articulo que está viendo
        :param request: objeto HttpRequest con los datos de la petición
        :return: objeto HttpResponse con los datos de la respuesta
        """
        message = None
        new_post = None

        article = self.get_current_article(request, nombre_de_usuario, articulo_slug)

        if not request.user.is_authenticated:
            message = _("No estás logado. Es posible que tu sesión haya caducado. Vuelve a hacer login antes de publicar el comentario.")
            comment_form = CommentForm()
        else:
            comment_with_article = Comment(owner=request.user, article=article)
            comment_form = CommentForm(request.POST, instance=comment_with_article)
            if comment_form.is_valid():
                comment_form.save()
                comment_form = CommentForm()

        #context = {'form': post_form, 'new_post': new_post, 'error': message}
        #return render(request, 'blog/new_post.html', context)

        return self.common(request, nombre_de_usuario, articulo_slug, comment_form, message)

articles/templates/articles/includes/articles_loop.html
{% load static %}
{% load i18n %}
{% load article_tags %}

        <div class="row">
            <div id="blog-posts" class="clearfix all-blog-post blog-inner without-sidebar">

                {% for article in articles_list %}
                    <article class="col s12 m6 l4 single-card-box single-post">
                        <div class="card">
                            <div class="card-image">
                                <div class="card-img-wrap">
                                    {% if article.media_url|is_imagen %}
                                        <div class="blog-post-thumb waves-effect waves-block waves-light">
                                            <a href="{% url 'article_detail' article.owner article.slug %}" title="{{ article.title }}"><img class="activator" src="{{ article.media_url }}" alt="{{ article.title }}">
                                            </a>
                                        </div>
                                    {% elif article.media_url|is_youtube %}
                                        <div class="blog-post-thumb videoPost">
                                            <iframe src="{{ article.media_url }}" allowfullscreen></iframe>
                                        </div>
                                    {% elif article.media_url|is_vimeo %}
                                        <div class="blog-post-thumb videoPost">
                                            <iframe src="{{ article.media_url }}" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                                        </div>
                                    {% endif %}

                                    <div class="post-body">
                                        <a href="{% url 'article_detail' article.owner article.slug %}" title="{{ article.title }}" class="post-title-link brand-text"><h2 class="post-title">{{ article.title }}</h2></a>
                                        <p class="post-content">{{ article.introduction }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix card-content">
                                {% include 'articles/includes/owner_info.html' with owner=article.owner item_date=article.publicated_at %}
                            </div>
                            <div class="clearfix card-content">
                                {% include 'articles/includes/fav.html' with article=article isDetail=False %}
                                <a href="{% url 'article_detail' article.owner article.slug %}#comments" class="left" title="Love this"><i class="material-icons">comment</i><span class="numb">{{ article.comments.all|length }}</span></a>
                                <a href="{% url 'article_detail' article.owner article.slug %}" class="brand-text right waves-effect">{% trans "leer más" %}</a>
                            </div>
                        </div>
                    </article> <!--./single blog post-->

                {% empty %}
                    {% trans "No articles yet." as the_message %}
                    {% include 'includes/info-message.html' with message=the_message %}
                {% endfor %}
            </div>
        </div>

articles/templates/articles/includes/fav.html
{% load i18n %}
{% load favourite_tags %}

<a class="left {% if isDetail %}post-like{% else %}like-button{% endif %} {% if user|faved:article %}active{% endif %} {% if user.is_authenticated %}js-favorite{% else %}no-click{% endif %}"
    data-article="{{ article.pk }}" data-fav-url="{% url 'fav_article' %}" data-unfav-url="{% url 'unfav_article' %}">
    {% spaceless %}
    <i class="material-icons">favorite</i>
    <span class="numb">{{ article.favourite_set.all|length }}</span>
    {% endspaceless %}
</a>

articles/templates/articles/includes/owner_info.html
{% load static %}
{% load i18n %}
{% load article_tags %}
{% load follow_tags %}

<div class="owner_info">
    <div class="chip {% if user.is_authenticated and user != owner %}with_action{% endif %}">
        <a href="{% url 'articles_by_user' owner %}">
            <img src="{% static "images/person.jpg" %}" alt="Contact Person">
            <strong>{{ owner.username }}</strong>, <time class="then" datetime="{{ item_date|date:"c" }}">{{ item_date.publicated_at }}</time>
        </a>
        {% if user.is_authenticated and user != owner %}
            {% if user|follows:owner %}
                <a class="js-follow action_remove_fav" data-owner="{{ owner.pk }}" data-follow-url="{% url 'follow_user' %}" data-unfollow-url="{% url 'unfollow_user' %}">
                    <i class="material-icons">check</i>
                </a>
            {% else %}
                <a class="js-follow action_add_fav" data-owner="{{ owner.pk }}" data-follow-url="{% url 'follow_user' %}" data-unfollow-url="{% url 'unfollow_user' %}">
                    <i class="material-icons">add</i>
                </a>
            {% endif %}
        {% endif %}
    </div>
</div>

articles/templates/articles/includes/underliner.html
{% load i18n %}

{% if user.is_authenticated %}
    <div class="post-underliner" id="underliner" style="display: none;">
        <a class="js-underline action_add_underline" data-article="{{ article.pk }}" data-underline-url="{% url 'underline_article' %}" title="Guardar subrayado">
            <i class="material-icons">add</i>
        </a>
        <div class="preloader-wrapper small active underliner-loader"><div class="spinner-layer spinner-brand-color-only"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div></div>
    </div>

    <div class="post-ununderliner" id="ununderliner" style="display: none;">
        <a class="js-underline action_remove_underline" data-article="{{ article.pk }}" data-underlined-text="-1" data-ununderline-url="{% url 'ununderline_article' %}" title="Eliminar subrayado">
            <i class="material-icons">delete</i>
        </a>
        <div class="preloader-wrapper small active underliner-loader"><div class="spinner-layer spinner-brand-color-only"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div></div>
    </div>

    <div id="underliner-error" class="underliner-error error-bg">{% trans "Se ha producido un error. Vuelve a intentarlo" %}</div>
{%  endif %}